insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('1','1','Bulbizarre','../images/Bulbizarre.png','650','La graine sur le dos de Bulbizarre est une réserve de nutriments. Il la fait doucement pousser en absorbant les rayons du soleil, et emmagasine de l\'énergie dedans en vue de son évolution. S\'il dépense trop souvent son énergie, il n\'évoluera pas car l\'ouverture de son bulbe dépend de ses réserves de nutriments.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('2','2','Salameche','../images/Salameche.png','650','De récentes études prouvent que la flamme qui brûle sur la queue de Salamèche indique son état de santé, mais aussi son caractère. S\'il se sent faible, la flamme sera toute petite. Et si par malheur sa flamme s\'éteint, il meurt, car c\'est le seul moyen pour lui de se refroidir.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('3','3','Carapuce','../images/Carapuce.png','650','Les bébés Carapuce sont extrêmement vulnérables à la naissance, car leur carapace est toute molle. C\'est pourquoi ils boivent régulièrement une eau riche en minéraux. Elle devient ensuite dure comme de la pierre. S\'il est menacé, il se réfugie à l\'intérieur et envoie un jet d\'eau à son agresseur.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('4','4','Pikachu','../images/Pika.png','1500','Les jours d\'orages, on peut apercevoir des Pikachu regroupés en haut des arbres ou des poteaux. Ces Pokémons attendent patiemment que la foudre leur tombe dessus, pour pouvoir recharger au maximum leur réserve d\'électricité. Quand il attaque, des milliers de volts sortent par ses joues rouges.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('5','5','Roucool','../images/Roucool.png','450','Les Roucool vivent principalement en forêt. Si l\'un d\'eux est obligé de se battre, il envoie du sable en battant des ailes. Il possède un sens de l\'orientation extraordinaire car il parvient toujours à retrouver son nid, où qu\'il soit. Avant l\'existence du téléphone, on les utilisait comme messagers.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('6','5','Rattata','../images/Rattata.png','450','Très mignon, Rattata est souvent l\'ami des enfants. Sauvage, il vit dans les marais ou les champs, mais il a une préférence pour les grandes villes car il y trouve facilement de la nourriture. Bien que petit, sa morsure est extrêmement puissante. Il prolifère très rapidement.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('7','5','Piafabec','../images/Piafabec.png','450','Petit et rapides, les Piafabecs sont pourtant très teigneux. Comme il ne sont pas très puissants, il vivent en clan d\'une trentaine de membres. S\'ils sont dérangés, ils poussent des piaillements assourdissant et fondent dans une attaque Aéropique. Leur petites ailes leur confèrent une rapidité surprenante.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('8','6','Abo','../images/Abo.png','450','Abo peut ravager toute une colonie de Piafabec ou de Roucool rien qu\'en dévorant ses œufs ou ses petits. Quand il s\'endort, il s\'enroule de façon à laisser sa tête au dessus, pour pouvoir mordre à tout moment. Son poison n\'est pas mortel, mais il provoque une terrible sensation de brûlure, comme le venin d\'une méduse.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('9','7','Sabelette','../images/Sabelette.png','450','Sabelette vit uniquement dans le désert, car il ne supporte pas du tout l\'humidité. Il boit en récoltant la rosée du matin. Pokémon plutôt farouche à l\'état sauvage, il est très affectueux avec son dresseur si celui-ci s\'occupe bien de lui. Le seul inconvénient : il ne peut pas s\'empêcher de creuser.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('10','6','Nidoran','../images/Nidoran.png','450','Nidoran femelle n\'aime pas combattre, et préfère se défendre grâce à ses épines empoisonnées. Ses dards sont plus petits que ceux du mâle, mais ils injectent le même poison. Apprivoisé, ce pauvre Pokémon souffre d\'un manque d\'affection car personne n\'ose la caresser.' );
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('11','8','Melofee','../images/Melofee.png','450','Mélofée est un Pokémon rare, qui vit uniquement sur le Mont Sélénite, à Kanto. Il est bizarrement apparut juste après qu\'une météorite se soit écrasée dessus, c\'est pourquoi les scientifiques pensent qu\'il est d\'origine extra-terrestre. Mignon, c\'est un ennemi redoutable, car son attaque Métronome est totalement imprévisible.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('12','2','Goupix','../images/Goupix.png','650','Quand il naît, le bébé Goupix n\'a qu\'une seule queue, qui se divisera plus tard en six s\'il est bien soigné. Même tout petit, il est parfaitement capable de se défendre car il sait cracher du feu, et si l\'ennemi ne recule pas, il envoie une attaque Onde folie. Son pelage tout doux lui donne l\'apparence d\'une peluche.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('13','2','Feunard','../images/Feunard.png','850','Feunard a longtemps été vénéré, car les gens pensaient qu`\'il était légendaire. C\'est un Pokémon gracieux, dont les nombreuses queues se balancent au rythme de ses pas légers. Beaucoup de dresseurs convoitent Feunard, pour sa beauté et pour sa puissance au combat.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('14','8','Rondoudou','../images/Rondoudou.png','850','Rondoudou ne peut pas s\'empêcher de chanter. S\'il se fait agresser, il entame une berceuse qui endort immédiatement son ennemi, et en profite pour prendre la fuite en roulant. Quand il chante, ses oreilles son automatiquement bouchées car sinon, il s\'endormirait lui-même.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('15','8','Grodoudou','../images/Grodoudou.png','950','Avec ses yeux immenses, Grodoudou rappelle une grosse peluche. C\'est un Pokémon très doux, très apprécié des enfants et des parents. Personne ne peut résister à sa berceuse. Si vous voyez un Grodoudou pleurer, ce n\'est pas parce qu\'il est triste mais c\'est parce qu\'il nettoie ses grands yeux.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('16','6','Nosferapti','../images/Nosferapti.png','450','Dans toutes les cavernes, il y a des groupes de Nosférapti. Il n\'en sortent jamais, sauf durant la nuit car une exposition prolongée au soleil leur brûlent la peau. Complètement aveugle, Nosférapti envoie des Ultrasons qui se répercutent sur les parois. Il les décrypte ensuite avec ses grandes oreilles, et peut ainsi éviter les obstacles.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('17','1','Mystherbe','../images/Mystherbe.png','450','Mystherbe reste sous terre toute la journée pour absorber des nutriments, vitaux pour sa croissance. Il ne sort qu\'à la tombée de la nuit, s\'il est sûr qu\'il est seul. Il en profite alors pour disséminer un peu partout ses graines. S\'il commence à secouer ses feuilles, c\'est qu\'il se prépare à lancer une poudre toxique comme Para-spore.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('18','1','Ortide','../images/Ortide.png','450','Ortide dégage une odeur pestilentielle s\'il n\'aime pas son dresseur ou s\'il ne se sent pas en sécurité. Quand il combat, il envoie sur son ennemi des poudres nocives, et l\'achève avec un liquide violet nocif : de l\'Acide. Il paraît que le liquide qui coule de sa bouche est sucré, mais personne n\'ose y goûter !');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('19','1','Rafflesia','../images/Rafflesia.png','650','A l\'état sauvage, Rafflesia vit uniquement dans la jungle. Quand il dort, il immerge sous terre la partie inférieure de son corps, tandis que sa fleur reste à l\'extérieur. Si une présence s\'approche, il libère inconsciemment une terrible poudre allergène, mortelle si on n\'agit pas à temps.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('20','1','Paras','../images/Paras.png','450','Paras a sur son dos deux champignons parasites, mais il ne semble pas en souffrir. Il arrive parfois d\'en croiser un avec trois champignons. Les scientifiques pensent que le champignon se transmet de génération en génération. Un Paras sans champignons sur son dos est destiné à mourir peu de temps après.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('21','6','Mimitoss','../images/Mimitoss.png','450','Les yeux de Mimitoss sont extrêmement perçants. S\'il est puissant, il peut même réussir à voir à travers de fins matériaux, comme de l\'herbe ou des feuilles. Il vit en général dans les grandes clairières tropicales, là ou les herbes sont hautes. Ce Pokémon passe son temps à courir dedans pour échapper à ses prédateurs.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('22','7','Taupiqueur','../images/Taupiqueur.png','450','Il est déconseillé de construire des habitations au dessus de galeries de Taupiqueur, car le poids pourrait faire tout effondrer. Ils sont en revanche très appréciés des agriculteurs, car apprivoisés, il rendent la terre bien meuble et creusent de parfaits sillons. Personne n\'a jamais vu un Taupiqueur en entier.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('23','5','Miaouss','../images/Miaouss.png','450','Miaouss est un Pokémon qui préfère largement vivre dans les villes plutôt que dans la nature. Il fouille les poubelles et se nourrit des déchets qu\'il y trouve. Apprivoisé, il passe son temps sur les genoux de son maître à se faire caresser. Beaucoup essayent de le forcer à utiliser son attaque Jackpot, mais Miaouss est trop rusé pour accepter.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('24','5','Persian','../images/Persian.png','850','Un Persian apprivoisé a le même caractère que son maître. Si celui-ci est mauvais, le Pokémon devient vite arrogant et agressif, sauf avec lui. Sauvage, il se tapit dans les hautes herbes et bondit brusquement, toutes griffes sorties, sur la malheureuse proie. Ses griffes acérées ne laissent aucune chance à la victime.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('25','3','Psykokwak','../images/Psykokwak.png','600','Psykokwak est un étrange Pokémon mi-aquatique, mi-psy. Ce pauvre Pokémon a la migraine en permanence, et quand celle-ci atteint son paroxysme, il utilise de puissants pouvoirs psy sans s\'en rendre compte. Il maîtrise alors l\'attaque Choc mental avec perfection.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('26','3','Akwakwak','../images/Akwakwak.png','850','Akwakwak est un excellent nageur, qui aime s\'entraîner à nager contre les courants marins pour se muscler. La perle sur son front lui prodigue de puissants pouvoirs psy, et les griffes au bout de ses pattes sont acérées. Beaucoup de dresseurs de Pokémons aquatiques aimeraient en posséder un.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('27','9','Ferosinge','../images/Ferosinge.png','500','Ferosinge est un Pokémon hyperactif qui ne dort pratiquement pas. Il se balance rapidement d\'arbre en arbre, et la moindre chose peut le mettre en colère. Quand il se bat, en général il ne compte pas sur sa puissance mais sur son agilité, et décoche rapidement des coups de griffe dans le dos de son ennemi.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('28','2','Caninos','../images/Caninos.png','450','Caninos est très fidèle. Loyal, il préfère se sauver plutôt que d\'attaquer son maître si celui-ci est injuste envers lui. Ce Pokémon est très apprécié car il est difficile de trouver plus affectueux et plus protecteur que lui. Il aime beaucoup jouer, c\'est pour cela que c\'est un grand ami des enfants.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('29','3','Ptitard','../images/Ptitard.png','450','Ptitard vit dans les lacs ou les étangs. Il peut nager à bonne vitesse car sa queue est une nageoire efficace mais par contre, il est beaucoup moins adroit sur terre car ses petites pattes n\'offrent pas un très bon équilibre. Une fine muqueuse lui entoure le corps, ce qui le rends très glissant.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('30','10','Abra','../images/Abra.png','950','Abra dort dix-huit heures par jour, mais pourtant, même éveillé, ses yeux restent fermés. Des dresseurs d\'Abra affirment que les rares fois où ils ouvrent leurs yeux, ceux-ci sont entièrement rouges. Il peut sentir à n\'importe quel moment quand il est en danger, et se téléporte pour se mettre en lieu sûr.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('31','9','Machoc','../images/Machoc.png','450','En général utilisé pour les tâches physiques, on trouve souvent des Machoc sur les chantiers. Ils adorent tout ce qui est musculation, et travailler pour les hommes est comme un jeu pour eux. Il ont des muscles spéciaux qui empêchent les courbatures et les claquages musculaires.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('32','10','Alakazam','../images/Alakazam.png','1200','Alakazam est un Pokémon qui n\'aime pas l\'effort physique. Il utilise sa Télékinésie pour toutes ses actions : manger, amener un objet à lui… Les scientifiques on démontré que si Alakazam utilisait des cuillères à café plutôt que des cuillères à soupes, leur pouvoir était moins puissant.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('33','1','Chetiflor','../images/Chetiflor.png','450','Les Chetiflor vivent en groupes dans la jungle, car il sont plutôt faible. Mais dès qu\'ils prennent confiance en eux et qu\'ils deviennent capables d\'utiliser l\'attaque Acide ou l\'attaque Fouet-liane, ils quittent leur clan. Ces Pokémons se nourrissent principalement d\'insectes volants qu\'ils piègent dans leur bouche.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('34','3','Tentacool','../images/Tentacool.png','500','Les Tentacool flottent en grands bancs à la surface de l\'eau. Ils vivent principalement au large, mais les vents forts peuvent les ramener près des côtes. Les deux grands globes rouges sur leur tête permettent d\'envoyer de puissants ultrasons, et leurs tentacules sont venimeux.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('35','3','Tentacruel','../images/Tentacruel.png','750','Un Tentacruel possède en moyenne quatre-vingt tentacules, tous très toxiques. Quand il se bat, il envoie de très puissants ultrasons, capables de rendre fou pour toute la vie. Il se sert habilement de ses tentacules pour attraper, pour trancher ou pour frapper.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('36','7','Racaillou','../images/Racaillou.png','750','Racaillou sait parfaitement se confondre parmi les rochers, et si par malheur quelqu\'un lui shoote dedans, il est capable de lui briser les deux chevilles. Mais en général, il préfère prendre la fuite. Ses bras musclés lui permet d\'effectuer de puissantes attaques Jet-de-pierre.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('37','7','Grolem','../images/Grolem.png','750','Grolem, trapu et lourd, a beaucoup de mal à se déplacer grâce à ses deux jambes. Il préfère bouger en roulant, c\'est pour ça que les cailloux qui constituent son corps sont plats. Il est beaucoup moins agile que ces précédentes évolutions, alors il se bat en provoquant des Séismes ou des Abysses.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('38','2','Ponyta','../images/Ponyta.png','600','Peu de temps après la naissance, Ponyta est capable de courir aussi vite que sa mère. Courir le rend heureux, sa crinière s\'embrase joyeusement quand il galope. Si son maître ne le fait pas suffisamment défouler, il dépérit rapidement. S\'il se fait agresser, les sabots de Ponyta peuvent fracasser le crâne de son adversaire.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('39','2','Galopa','../images/Galopa.png','850','Au galop, la vitesse maximale d\'un Galopa est de 240 km/h. S\'il est en confiance, sa crinière n\'est pas brûlante et il aime être monté. Il a sans cesse besoin de se prouver qu\'il est le plus rapide, c\'est pour cela qu\'il défie tout ce qui bouge dans une course, où il sort vainqueur à chaque fois.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('40','2','Ramoloss','../images/Ramoloss.png','650','Ramoloss peut passer une journée entière à se prélasser au soleil sans rien faire. Il n\'est pas très vif d\'esprit, et il a à chaque fois un temps de réaction pour comprendre ce qu\'on vient de lui dire, ou pour comprendre ce qu\'il vient de se passer. Il ressent la douleur seulement au bout de cinq secondes.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('41','2','Flagadoss','../images/Flagadoss.png','850','Un Flagadoss ne peut apparaître que si un Kokyas mord la queue d\'un Ramoloss. Il développe alors plus largement ses pouvoirs psychiques, mais n\'en devient pas plus dégourdi pour autant. Son attaque Amnésie peut paraître inutile, mais elle le rend en réalité plus puissant en augmentant presque toutes ses capacités.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('42','4','Magneti','../images/Magneti.png','750','Magnéti est irrésistiblement attiré par toutes les sources de courant électrique. Quand il trouve un objet qui fonctionne à l\'électricité, il se colle dessus pour en absorber l\'énergie. Il lévite en envoyant un léger champs électrique. Ses attaques Tonnerre peuvent déclencher des crises d\'épilepsie.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('43','4','Magneton','../images/Magneton.png','750','Un Magnéton est une association de trois Magnéti, soudés par un puissant courant électrique. Leurs aimants attirent toute l\'électricité contenue dans l\'air. Magnéton est très excité les jours d\'orages, et il essaye à tout prix d\'attirer la foudre sur lui. Son attaque Cage-éclair paralyse à tous les coups son ennemi.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('44','7','Canarticho','../images/Canarticho.png','850','Canarticho ne se sépare jamais de son poireau car il lui sert à se défendre. Il le brandit habilement pour frapper, ou trancher. Les gens pensaient que ce poireau possédait des vertus particulières, mais c\'est juste un banal légume. C\'est un Pokémon solitaire.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('45','7','Doduo','../images/Doduo.png','650','Doduo est un Pokémon qui vit, à l\'état sauvage, dans les grandes plaines, où il peut courir à loisir. Ne pouvant pas voler, il a développé ses pattes pour échapper à ses ennemis. Ce Pokémon possède bien deux cerveaux, mais une seule tête est capable de contrôler le corps ; c\'est pour cela que la deuxième tête est toujours agressive.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('46','7','Dodrio','../images/Dodrio.png','750','Les trois têtes de Dodrio possèdent leur propre caractère. Les trois têtes ne dorment jamais en même temps, car elles se relaient pour monter la garde.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('47','3','Otaria','../images/Otaria.png','950','Otaria possède un épaisse couche de graisse qui le protège des eaux glacées. Son pelage blanc le confond parfaitement sur la neige, car il vit uniquement dans les climats glacés. Nager dans une eau dont la température descend en dessous de zéro ne lui fait pas peur.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('48','3','Lamantine','../images/Lamantine.png','1200','Lamantine est si gracieux que, jadis, les marins le prenait pour une sirène. Pour se reposer, il se hisse sur les Icebergs, sa peau dure est fournie d\'une couche de graisse qui l\'isole parfaitement du froid. Il sait se déplacer sur terre, mais il est beaucoup plus à l\'aise dans l\'eau pour lancer ses Onde Boréales.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('49','6','Tadmorv','../images/Tadmorv.png','450','Le liquide visqueux qui compose le corps de Tadmorv est si toxique, qu\'une fois qu\'il passe sur la terre, celle-ci devient infertile. Quelques gouttes tarissent un étang. Mais heureusement, il n\'aime pas tellement la vie sauvage et préfère vivre dans les grandes villes, où il s\'installe dans les égouts et les canalisations.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('50','6','Grotadmorv','../images/Grotadmorv.png','650','Grotadmorv dégage une odeur particulièrement atroce. Il n\'est pas rare de voir parmi un groupe de Tadmorv un imposant Grotadmorv. Dans les égouts, il ne dérange personne mais s\'il vient s\'infiltrer dans les canalisations, il provoque un bouchon. Il se nourrit de fruits pourris et de cadavres en décomposition.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('51','3','Kokiyas','../images/Kokiyas.png','500','Kokyas est irrésistiblement attiré par la queue des Ramoloss. Dès qu\'il en voit une, il ne peut s\'empêcher de la mordre. S\'il est attaqué, il se réfugie dans sa coquille, ne l\'ouvrant que pour lancer des Pistolets à O. Sa langue analyse l\'environnement extérieur, il peut sentir la chaleur des autres Pokémons grâce à elle.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('52','6','Fantominus','../images/Fantominus.png','500','Le corps de Fantominus n\'est pas solide, il est uniquement gazeux. Il adore se réfugier dans les maisons abandonnées, et effrayer les visiteurs occasionnels avec des hallucinations. Quand il fait une attaque Léchouille, sa langue se matérialise par un phénomène inconnu. Il est impossible à atteindre par des attaques physiques.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('53','6','Spectrum','../images/Spectrum.png','600','Les Spectrum sauvages adorent effrayer les passants en faisant d\'horribles grimaces. Il est passé maître dans les attaques de type spectre, le rendant encore plus terrifiant. Apprivoisé, ce Pokémon est très fidèle et il ne perd pas une occasion de faire rire son dresseur.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('54','5','Onix','../images/Onix.png','450','Onix vit sous terre, en creusant à parfois 90 km/h. Son terrain de prédilection est la montagne, lui permettant d\'exposer sa large gamme d\'attaques de type sol et roche. Il vit en général loin des villages, mais un de ces Pokémon déclenche à chaque fois un cri d\'admiration lorsqu\'il est aperçu à l\'état sauvage.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('55','10','Soporifik','../images/Soporifik.png','450','Soporifik a une mauvaise manie, qu\'il ne perd jamais même apprivoisé : il mange les rêves des hommes, il ne peut pas s\'en empêcher. S\'il mange un cauchemar, il tombe malade. Quand il a faim, il n\'attend pas de trouver une victime endormie : il s\'en charge lui même en l\'hypnotisant.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('56','3','Krabby','../images/Krabby.png','450','Les Krabby vivent sur les berges des lacs, et sur les plages. Ils ne peuvent pas s\'empêcher de faire des bulles. Krabby paraît faible, mais ses pinces peuvent briser un rocher en mille morceaux. Ce Pokémon est incapable de se déplacer vers l\'avant : il ne sait marcher que latéralement.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('57','4','Voltorbe','../images/Voltorbe.png','450','La première fois qu\'on a aperçu Voltorbe, c\'était dans une usine de Pokéballs. Personne ne sait comment il est apparu sur terre. Il se déplace en roulant, en envoyant sans faire exprès quelques étincelles. Cette simili pokéball se défend grâce à des attaques Tonnerre et Grincement.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('58','10','Noeunoeuf','../images/Noeunoeuf.png','450','Un groupe de Noeunoeuf est toujours constitué de six membres solidaires, attirés entre eux comme des aimants. Si l\'un d\'entre eux se perd, ils utilisent leur énergie télépathique pour se retrouver. Comme ils n\'ont pas de jambes, il se déplacent en petits bonds organisés. La coquille fendue indique la prochaine évolution.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('59','10','Noadkoko','../images/Noadkoko.png','450','Les Noadkokos vivent dans la jungle en bande. Leurs têtes sont chacune particulière, toutes ont leur propre sentiment. Quand l\'une d\'elle tombe, elle se transforme en Noeunoeuf et part immédiatement à la recherche d\'un groupe. Ce Pokémon utilise sa télépathie pour communiquer.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('60','7','Osselait','../images/Osselait.png','500','Osselait porte toujours son casque en os sur la tête. Personne n\'a jamais vu ce Pokémon sans. Il fouille parmi les carcasses pour trouver un os, qu\'il utilisera comme massue. Il est très sensible, et se met à pleurer s\'il a faim, froid, soif ou peur mais quand il se bat, il peut être redoutable.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION)values ('61','9','Kicklee','../images/Kicklee.png','750','Les jambes de Kicklee peuvent s\'allonger et se rétracter à volonté, comme des élastiques. C\'est un pro des arts martiaux, mais il se bat uniquement avec ses jambes. Seul, il s\'entraîne constamment à diverses attaques de type combat : Mawashi-guéri, Pied sauté ou Pied voltige.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION)values ('62','9','Tygnon','../images/Tygnon.png','750','Tygnon aime taper avec ses poings. Il est très rapide, décochant à ses ennemis des coups fulgurants. S\'il s\'entraîne suffisamment, il peut maîtriser trois éléments, le rendant alors difficile à battre : Poing feu, Poing foudre et Poing glace. Son jeu de jambe lui permet d\'esquiver les coups.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('63','5','Excelangue','../images/Excelangue.png','850','La langue d\'Excelangue fait deux fois la taille de son corps. Ce Pokémon est un véritable glouton, il mange tout ce qu\'il voit, l\'attrapant en déroulant son immense langue. Il enregistre le goût dans sa mémoire, qu\'il n\'oublie jamais. Il produit une salive spéciale, qui paralyse tout ceux qui entrent en contact avec elle.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('64','6','Smogo','../images/Smogo.png','525','Le corps de Smogo est principalement constitué de gaz toxiques. En respirer en petite quantité provoque des irritations et des reniflements mais une trop grosse dose peut s\'avérer mortelle. Il ne faut surtout pas l\'emmener dans un endroit chaud car sinon, il explose.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('65','3','Leviator','../images/Leviator.png','1500','Terrifiant et puissant, Leviator peut rentrer dans des aspects de rage terrifiant : raser une ville entière ne lui fait pas peur, et de nombreux récit historiques racontent que pendant les guerres, il apparaissait et rasait des régions entières.. Personne ne sait expliquer comment un ridicule Magicarpe peut se transformer en un monstre si terrible.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('66','3','Hypotrempe','../images/Hypotrempe.png','500','Hipotrempe résiste aux forts courants marins en s\'accrochant aux coraux ou aux pierres grâce à sa queue. Il se nourrit de mousse, mais son repas préféré reste les insectes volant. Il sort sa tête de l\'eau, et attends qu\'il passe un insecte pour lui cracher un jet d\'encre.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION)values ('67','3','Hypocean','../images/Hypocean.png','650','Les aiguillons sur le dos d\'Hypocéan sont empoisonnés. S\'il est dérangé, il crache un jet d\'encre pour s\'enfuir mais si l\'agresseur persiste, il lui envoie une rafale de piquants venimeux. Pour dormir, il s\'ancre solidement aux rochers avec sa queue en spirale.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION)values ('68','3','Poissirene','../images/Poissirene.png','650','Poissirène est un magnifique Pokémon doté de nageoires qui ondulent avec grâce dans le courant. Il à longtemps été considéré comme le symbole de la grâce et de la beauté. Cependant il peut être un adversaire redoutable car quand il charge, sa corne est dirigée vers l\'avant pour faire front.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('69','3','Poissoroy','../images/Poissoroy.png','850','L\'automne est la saison nuptiale des Poissoroy. On peut les voir en grand groupes dans les rivières pour essayer de plaire aux femelles. C\'est pendant cette saison que ses nageoires prennent les plus belles couleurs. Il défend sa femelle avec fougue, en lançant des attaques Empal\'corne ou Coud\'korne.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('70','3','Stari','../images/Stari.png','850','Stari est un étrange Pokémon, constitué d\'un seul organe principal : un magnifique joyau qui brille de mille feux, le cœur. Ces mystérieuses créatures ont le pouvoir de se régénérer entièrement, tant que le cœur est intact : si une de ses pattes tombe, elle est immédiatement reformée.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('71','3','Staross','../images/Staross.png','950','Le cœur de Stari a évolué pour donner un joyaux encore plus resplendissant et un nouveau pokémon : Staross. Son joyaux brille de différentes couleurs en fonction de la lumière, de l\'angle de vue et de l\'humeur du Pokémon. Si celui-ci est brisé durant un combat, il meurt.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('72','8','M.Mime','../images/Mime.png','950','Mr mime est passionné par le fait d\'imiter des choses invisibles. Ses doigts produisent une onde chimique qui rend l\'air palpable, et avec le temps et l\'expérience, il peut devenir capable de créer de véritables objets. Ne le dérangez jamais en train de mimer, car sinon il vous punira avec une volée de claques.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('73','11','Insecateur','../images/Insecateur.png','1200','Insecateur possède deux armes meurtrières : sa vitesse combinée avec l\'utilisation de ses lames. Les petites ailes sur son dos sont incapables de le faire voler sur une longue distance, mais elles lui donnent une vitesse si impressionnante que lorsqu\'il il se déplace, il donne l\'illusion d\'être en groupe. Ses lames couperaient un tronc d\'arbre d\'un seul coup.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('74','8','Lippoutou','../images/Lippoutou.png','900','Lippoutou est un étrange Pokémon humanoïde, qui se déhanche de droite à gauche d\'une drôle de façon en marchant. Les gens qui le croisent sont soudains pris d\'une envie de se déhancher comme lui, c\'est un phénomène inexpliqué. Il aime par dessus tout embrasser les gens, mais s\'il le souhaite, il peut les paralyser ainsi.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('75','4','Elektek','../images/Elektek.png','850','Comme beaucoup de Pokémons Electriks, Elektek se regroupe sur les hauteurs en cas d\'orages. C\'est un combattant qui fait sortir l\'électricité par ses deux antennes placées sur son front. En faisant parcourir ainsi le courant sur son corps, il devient impossible à toucher physiquement, sous peine d\'électrocution.');
insert into pokemon (id_pokemon,ID_TYPE,name_pokemon,IMG_POK ,PRICE_POK,DESCRIPTION) values ('76','2','Magmar','../images/Magmar.png','750','Dans les volcans en activités, vous pourriez trouver des Magmar en train de prendre un bain de lave. Ces Pokémons sont totalement insensibles à la chaleur, puisque leur corps est en constante fusion. Il suffit qu\'un combat démarre pour que son corps s\'embrase violemment.');





insert into TYPE (ID_TYPE,LIB_TYPE) values ('1','Plante');
insert into TYPE (ID_TYPE,LIB_TYPE) values ('2','Feu');
insert into TYPE (ID_TYPE,LIB_TYPE) values ('3','Eau');
insert into TYPE (ID_TYPE,LIB_TYPE) values ('4','Electrique');
insert into TYPE (ID_TYPE,LIB_TYPE) values ('5','Normal');
insert into TYPE (ID_TYPE,LIB_TYPE) values ('6','Poison');
insert into TYPE (ID_TYPE,LIB_TYPE) values ('7','Sol');
insert into TYPE (ID_TYPE,LIB_TYPE) values ('8','Fee');
insert into TYPE (ID_TYPE,LIB_TYPE) values ('9','Combat');
insert into TYPE (ID_TYPE,LIB_TYPE) values ('10','Psy');
insert into TYPE (ID_TYPE,LIB_TYPE) values ('11','Insect');





insert into t_user(usr_name, usr_salt, usr_password, usr_role) values('JohnDoe', 'YcM=A$nsYzkyeDVjEUa7W9K', 'L2nNR5hIcinaJkKR+j4baYaZjcHS0c3WX2gjYF6Tmgl1Bs+C9Qbr+69X8eQwXDvw0vp73PrcSeT0bGEW5+T2hA==', 'ROLE_USER');

